dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - docbook-xml
    - docbook-xsl
    - libxml2-utils
    - xsltproc
script:
- python -m compileall -f .
- nosetests --with-doctest --verbose lib/varietes.py
- xmllint --nonet --noout --valid doc/*.xml
- python setup.py install --user
- export PYTHONPATH=~/.local/lib/python$TRAVIS_PYTHON_VERSION/site-packages"${PYTHONPATH:+:$PYTHONPATH}"
- command -v djvusmooth
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 djvusmooth | grep -A 10 -w DJVUSMOOTH

# vim:ts=2 sts=2 sw=2 et
