dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - docbook-xml
    - libxml2-utils
script:
- python -m compileall -f .
- nosetests --with-doctest --verbose lib/varietes.py
- xmllint --nonet --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
